---
title: "Intro To Citrix And Linux"
author: "Bronson, Debbie, Sean and Marc"
date: "10/7/2015"
output: html_document
---

Welcome to the introductory course for computer resources here at SCRI.  This course will cover a basic introduction to the SCRI Citrix environment and also will introduce you to basic tools in linux.  If you have a bad case of CLAS (command line aversion syndrome), then this course should help you get on the road to recovery.


Here is a list of topics that should be covered by the end of this course:

# Introduction to Citrix

# Introduction to Linux: 

### What is Linux?  

Linux is a free open sourced operating system based on Unix.  It's technically not unix, but in practice it might as well be.  Unix is a dinosaur of the computer world and has been around forever.  The reason it's still here is because it works really well and people still find it quite useful today.

### How is it organized?  

There are many flavors of unix, but most of them have the same basic directory structure.  You don't need to know about a lot of it in order to use it.  But you should know a couple of things.  The 1st is that the root directory is the base for the whole system.  Unless you are the system admin or are installing software or something, you probably don't belong down there.  More commonly you want to be in your home directory.  Your home is at ~/  We will talk more about this is a minute.

### Why do people use it?

People like unix because it is powerful and flexible tool for efficiently getting certain kinds of work done.  This is especially true for work that has never been done before or that requires the creation of customized work flows.  If this sounds familiar that's because this is the same kind of work that people often need to do to manage data in science.  And this is why so many scientists have found linux to be a useful platform for developing new work flows.  Everyone agrees that graphical interfaces can be nice.  But the odds that you will find one that already does exactly what your experiment needs get vanishingly small starting with the moment you do anything interesting.


# Introduction to the command line: 


### What is tab-completion?

Before you type anything, please locate the tab key in the upper left part of your keyboard. You are going to be hitting that key a lot. That is because in Linux if you start to type something, even it you only know the first letter, you can hit the tab key for suggestions about what should come next. Go ahead and try it!  Type `pw` and then hit the tab key for suggestions about what we might do next...

### Case sensitivity.

In Linux, the case of a letter matters. 'A' is not the same thing as 'a' etc.  So watch out for changes in case.  You will notice that some people prefer to name things using alternating lowercase and uppercase letters like this: 

```
myFile.txt
``` 
That style is called camel case.  

Other people prefer to use underscores like this:

```
my_file.txt
```

And still other people prefer all lowercase like this:

```
myfile.txt
```

Whatever style you prefer, these all have one thing in common: no spaces.  You shouldn't use white space in filenames when using linux.  You technically can do it, but everyone agrees that it's not worth it since you have to escape all your white space characters...  And this is a huge inconvenience.  So if you give someone a file like this in linux you should expect that they will be annoyed with you.



### pwd, / and ~/

This is how you know where you are:

```
pwd
```

`pwd` means print working directory.  It will tell you where in the file system you are by giving you the full path starting with root.


The root of a unix filesystem always starts with `/`.  So when you run `pwd`, you will alway state your current path relative to root.  `~/` is shorthand for your home directory.  But if you go to your home directory, you will be able to see the full absolute path by using `pwd`.

### Directories, executables and files

Directories are for storing stuff, executables do things to stuff and files are stuff.  In Linux a full directory path will start with root and end with another `/` and use more `/`'s in between as separators for each subdirectory.  On most command lines directories will be colored to indicate that they are different from the files.  And in linux most executables are stored somewhere else, so you won't normally see those unless you are invoking them as commands.


### cd, . and ..

`cd` means change directory.  You call that command followed by a single argument to indicate which directory you want to change to.  

`.` means here.  You use it to indicate that the path to something is where you are right now.  

And `..` means one directory up from here.


### ls

`ls` is used to list a directory.  Which directory does it list?  That would be the second argument.  For example, the following command would list the contents of the root directory

```
ls /
```

And this would list the current directory.
```
ls .
```

But in practice when people want to list the current directory, they leave out the implicit `.` like so:
```
ls
```

And when I use this command, it tends to look like this:
```
ls -alh
```
Which translates to: list the directory, but list all the files (even hidden ones), and use the long format, and make the sizes human readable.  How did I ever learn to do that?


### man

Well I used the man command to learn more about `ls`.  You can use the man command to pull up a manual about any linux command like this:

```
man ls
```

When you are done looking at it, hit the `q` key.


### flags

And while we are looking at an example of some, lets talk about `flags`.  In Linux, there are special arguments called flags.  They come after the command and always follow a dash (like `-alh` above).  What they do is modify the meaning of a function.  The man page for a command should always tell you about the different flags that a command supports.



### What are permissions?

Another thing you might have noticed about my longer form use of `ls` is that it puts a string of characters in from of each file and directory.  Lets look at a toy example:

```
-rw-r--r-- 1 username rleQAS_SCRI-Sudo 8.2K Oct  7 17:21 file.txt
```

Permssions are used by Linux to control who can do things. They can be applied to (u)sers, (g)roups, (o)thers, or (a)ll.  (u)sers means the user who owns (created) the file while (g)roups mean the group that the file belongs to, and (o)thers means people who are not in these first two categories.  In Linux everything belongs to someone, so ownership and permission to act accordingly is a big deal.  Also true in Linux, is that groups of users are tracked and assigned to each file.  But each of these categories (user, group or other) can have separate permissions set to control whether people are allowed to (r)ead, (w)rite or e(x)ecute them.  Returning back to the mysterious string of ten characters mentioned above, it is actually broken into 4 sections: 

1) The very first character doesn't actually have to do with permissions.  It just indicates the kind of thing that something is. For example if it starts with `d`, then it's a directory etc.  In general, you won't need to spend a lot of time thinking about this first character.
2) The next three characters: indicate the (r)ead, (w)rite and e(x)ecute policy for the (u)ser
3) The next three characters: indicate the (r)ead, (w)rite and e(x)ecute policy for the (g)roup
4) The last three characters: indicate the (r)ead, (w)rite and e(x)ecute policy for the (o)thers

Based on this, we can see that for the file above the permissions are set to be readable and writable for the owner of this file, but only readable by others.  If you ever need to change the permissions on a file, you would do that by using the `chmod` command.  Also, you may not be allowed to change permissions for some files and directories depending on who they belong to and what kind of access priveleges you have.



#### __Exercise L1:__ 

Display the working directory of your home directory.  Now look around to see if you can find the working directories for the other users.  Are you allowed to see the contents of those directories?  How do you know?


### mkdir

Sometimes you will need to make a new directory.  For that there is the mkdir command.
```
mkdir myDir
```

### touch

And sometimes you will just need to create an empty file.  Maybe later on you want to write something to it, but right now you just want to reserve that filename.  For that you can use the `touch` command.  Here we use touch to create a file inside of our new directory:

```
touch myDir/test.txt
```

### text editors

Linux is rife with powerful text editors.  Some of them (like vi or emacs) are so powerful that they could each have their own course.  Today lets look at a very simple and common one: `nano`.

```
nano myFile.txt
```

That command will launch the nano editor.  Once inside you will be able to type in text of interest.  When you want to leave you can look at the bottom of the screen and you will see commands abbreviated like this: ^X 

`^X` means `control-X`.  It's a hint about how to give that command.  Do it now to exit out of nano and feel free to save your work on the way.


### less is more

Sometimes less is more.  And when you are using linux suddenly `less` literally is a more advanced version of the `more` command.  The `more` command was long used for looking at large text files.  And `less` does the same basic job as `more`.  So now that you know that, you should expect that the following command will let you look at the file `myFile.txt`:

```
less myFile.txt
```

And when you were done you could exit by again pressing `q`.  Why the similarity to `man`?  Because man is actually using `less` to display the contents of the manual pages.  It's not the only time you will see that happen either.  Tools in Linux gets reused a lot.

### cp, mv and rm

`cp` copies a file to another place.  `mv` moves a file (and so does not leave the original behind).  Here is an example of each of these:

```
cp file.txt filecopy.txt
mv file.txt ..
```

The first of these commands copies `file.txt` to another file with a different name `filecopy.txt` in the same directory.  The second command moves file.txt up a directory from where it is currently located.

But sometimes you just want to get rid of something altogether.  `rm` will do that for you.  Here is an example that just removed file.txt:

```
rm file.txt
```

Another common case with rm is when you have a directory and you want to remove it AND everything in it  When that happens you can tell rm to remove things recursively like this:

```
rm -r myDir
```

Where myDir and everything in it will be deleted.  Obviously using the -r flag with rm can be dangerous. So be caregful!


### dos2unix

dos2unix is a useful command to know about. Text files from windows will typically have different line endings from text files from unix. And that can be a problem if you need to parse files by line. dos2unix fixes files that have been formatted for windows so that the line endings are the same.  So the following command will fix the `myFile.txt`.

```
dos2unix myFile.txt
```



#### __Exercise L2:__ 

TODO: We need something like some 'toy tab files' for people to get. And some creative ideas about what they should do with them.



### What are wildcards?

In linux you can use `*` as a wildcard to indicate more broadly which things you mean.  So for example, if I have to files that both end with `.txt` then I can move them both into myDir by doing this:

```
mv *.txt /myDir
```

Wildcards are useful for a whole host of other circumstances.  But be careful.  If you use them with commands like rm, you might end up wishing that you could rewind time.
 

### cat

Cat is useful for streaming the contents of a file.  As a quick example the following use of cat would dump the contents of `myFile.txt` to the screen.  So by itself `cat` is not so useful.

```
cat myFile.txt
```

But: the more common use for `cat` is to send a command to a pipe.  What is a pipe you say?


### What are pipes?

So glad you asked! A pipe is a way of moving data around in unix.  Technically, it is an "operator" (like "+" and "-").  And you use it to indicate something specific that you want to happen between a couple of other things.  Let me give an example to clarify:

```
cat myFile.txt | less
```

Here cat is streaming the contents of myFile "in" to a pipe.  Where doed the data go next?  Well in the example above it goes "in" to the less command.  So when you see the `|` operator, what it means is that the output of the thing to it's left is being sent "in" to the thing to it's right.  Just like a pipe would.  

Ok, I will admit that the example above could be a lot more interesting.  Right now you are probably wondering why not just use less on the file like a normal person?  But just wait till we show you some other tricks that you can use with pipe.  I promise we will make this worth your time...


### grep

The grep command is usually used to find strings in text files. For example you could search a file called `file.txt` for the string `var` like this:

```
grep 'var' file.txt
```

This is useful all by itself, and grep is extremely powerful since it is a fast and efficient way to search your files for lines that match.  But look at what happens when we pair it with a pipe and less like above:

```
grep 'var' file.txt | less
```

Now if I have a Large number of search results, I can easily page through them (or use the additional search feature inside of less).  Or I can take the results of the 1st grep search and send that along to another grep search like this:


```
grep 'var' file.txt | grep 'car' | less
```



### > and >>

What happens if you link together a set of pipes that does something useful?  Then you might want to save the out put.  This is when you would use the "bent pipe" or `>`

```
grep 'var' file.txt | grep 'car' > saveFile.txt
```

And sometimes, you might want to simply append to an existing file without overwriting it.  In that case you would use the "double bent pipe" or `>>`.  So if we repeat the example above, then you will see that we have appended the same thing into `saveFile.txt`.

```
grep 'var' file.txt | grep 'car' >> saveFile.txt
```

#### __Exercise L3:__ 

TODO: need an idea about what people can do with pipes, cat and grep.




### split

Sometimes you may have a really big file that you need to split into smaller pieces.  the `split` command will let you easily do that.

### head and tail

Another thing that happens with large files is that you may only want to see (or process) the first few lines.  The `head` and `tail` commands will allow you to look at the first or last few lines of any given file.

### sort

Need to put the contents of a command into a particular order?  The `sort` command is your friend for this task.

```
sort test.txt
```


### uniq
Want to filter out rows that are not unique?  Use the `uniq` command.

```
sort test.txt | uniq
```


### cut

Cut is especially useful if you have to deal with delimited files.  It allows you to get data by specifying a delimiter and then extract only a piece of interest.  For example, the following gets the 2nd column from a tab delimited file

``` 
cut -f 2- testTabs.txt
```

### wc

The `wc` command is the word count command.  This command is sort of a curiosity on it's own, but in combination with other commands it can become very useful.  For example, if you wanted to know how many things were in the current directory you could do this:

```
ls | wc
```



### find

The find command is for finding files in the filesystem.  But it is actually VERY powerful because like everything else today it can be paired with the other toys in the Linux toybox.  The find command takes a couple of arguments. The 1st is the part of the directory to search in and the secons is what to look for.  A common way to use find is to find a file with a specific name.  So to find a file named `bob.txt` in your local directory could could do this

```
find . -name 'bob.txt'
```

But as I stated before find is quite powerful.  You can also do partial matches, and choose from a huge array of other flags etc. to find things depending on what you happen to remember.


#### __Exercise L4:__ 

TODO: need an idea about what people can do with pipes and the other fun stuff here like find, uniq and word count.




### who and top

Sometimes you want to know who else is logged in. IOW, if there are multiple machines to work on, you might prefer to work on a less crowded one...

Other times when you log into a computer you might be wondering what it is doing overall.  This is what the top command is for.  If you call top, you will get a high level overview of what the computer is doing right now.  Top will tell you what processes are running, and how many resources they are using.  And by using it you can spot problems.  For example, you might want to know about long running processes that are consuming up all the system resources and slowing you down.


### ps and kill

Top is useful for seeing whether there is a problem, but it updates frequently and only tends to display long running processes that are using a lot of resources.  Sometimes you just want to see all the things that you are running.  `ps` is a good way to list all the processes that you have running.  This command will list all the processed run by a particular user:

```
ps -U username
```

Once you have done that, you will see an output that looks like this:


```
[username@EWRLNXRD29 SCRICompBioCourses]$ ps -U username
  PID TTY          TIME CMD
 5101 ?        00:00:00 sshd
 5106 ?        00:00:00 sshd
 5108 ?        00:00:00 sftp-server
```

The `PID` stands for the process identifier.  It's a unique number that can be used to specify precisely which process you mean.  This is important, because if you make a mistake and accidentally launch some long running resource hogging process, you might not want to wait (or make others wait) for it to finish.  In that case you might need to `kill` it.  Here is an example of how you could do just that:


```
kill 5106
```

The above command will kill the process where the PID = 5106.



#### __Exercise L5:__ 


TODO: need an idea of how they can start a bad process and then find and kill it.



### echo

Sometimes you may need to look at the contents of shell variables.  Linux systems will often use environment variables and sometimes you might need to see what these have been set to.  The `echo` command will let you see what these values are.  When you use the echo command, you have to prefix any variable names with `$`.

```
echo $PATH
```


-----------------------------------------------------------------------------------------------------------------
   
      
### __Answers for Exercises__ 

Here you can find answers to the questions posed above.   


##### __Answer for Question L1:__

Display the contents of home

```
cd ~/
ls
```

Find where other home dirs are located
```
pwd
cd ..
ls
```
Are you allowed to see other working directories?

```
ls -l
```
No: the permissions prevent this





##### __Answer for Question L2:__


##### __Answer for Question L3:__


##### __Answer for Question L4:__


##### __Answer for Question L5:__

