---
title: "Coding with R"
author: "Marc, Sean, Bronson and Debbie"
date: "11/25/2015"
output: html_document
---

Welcome to our third course which aims to take you from a basic ability to interact with the language to one where you are able to write your own code.  From the outset we will try to warn you about bad habits so that you will avoid making some of the mistakes that most other people make when they start programming in R.

Here is a list of topics that should be covered by the end of this course:

# Basic system tools
### system.time
### system()
### getwd(), setwd()
### dir(), file.remove(), file.rename()


***
####  <span style="color:blue">__Exercise R:__</span> 
***


# How to create basic functions
### The basics
### Flow control
#### if, else
#### switch

***
####  <span style="color:blue">__Exercise R:__</span> 
***


# Writing good code in R
### check your arguments when writing functions
### write short functions
### Don't repeat yourself (DRY)
### always check if someone else has solved the problem

***
####  <span style="color:blue">__Exercise R:__</span> 
***


# Some pitfalls specific to R
#### forgetting to vectorize
#### the loop with a big appetite
#### hidden arguments and default behaviors [,drop=TRUE]

***
####  <span style="color:blue">__Exercise R:__</span> 
***


# Literate programming.
### What is an .Rmd file?
### Reproducible research

***
####  <span style="color:blue">__Exercise R:__</span> 
***


# version control.
### So you don't lose your mind

***
####  <span style="color:blue">__Exercise R:__</span> 
***


# Bioconductor. 
### How to find good packages for your problem (biocviews)

### How to use workflows
### Fun Examples of things you can learn from workflows: (RNA-seq, chip-seq, etc.)

***
####  <span style="color:blue">__Exercise R:__</span> 
***




# How to write S4 methods (and when)
### methods are not the same thing as functions
### Why would you do this? (elegant dispatch)
### What is a Generic and when do I need to care?


# Write good packages (this is another course)
#### use your namespace (don't export everything)
#### use live code blocks and unit tests
#### use toy examples to verify that code works
 





